### ISSUE TITLE
Suit ranking

### ISSUE THREAD

**Issue by Allybag** [winstonrc/casino#76]
Hey Winston, this is Alex from RC.

It looks like in casino_poker/src/hand_rankings.rs:193 you rank all flushes the same.

When tie breaking flushes, the logic is the same as for High Card, for example **K**9752 beats **Q**9732, and K975**3** beats K975**2** (https://www.888poker.com/how-to-play-poker/hands/flush-poker-hand-ranking/)

The only way for two flush hands to tie is if the board is a complete flush, and players each either have none of that suit, or only cards below the lowest rank on the board.

You're right though that in Texas Hold'em there can only ever be a flush of one suit.

Cool project!

**Comment by Allybag** [comment]
Also one other thing, is that every hand in poker is actually exactly 5 cards, even hands like a pair.

So, for example KKJQ**8** beats KKJQ**7**, are both one pair of Kings, but the first hand beats the second hand on the fifth card.

Hands like straights, flushes, and full house already contain five cards, but high card, pairs, two pairs, three of a kind and four of a kind all also include as many of the highest cards on the board or in the hand as required to make up to five cards, and all of these cards are also used as tie breakers.

**Comment by winstonrc** [comment]
This is super helpful thank you! I asked a poker player about flushes and seem to have received bad advice, so I'll have to fix this.

As to your second comment, I should already have that implemented if you want to double check it. The kicker logic could be cleaned up, but it's located here:

https://github.com/winstonrc/casino/blob/6496303136201a715dbcf26182d50efac1ea93be/crates/casino_poker/src/games/texas_hold_em.rs#L545

I put it in the Texas holdem logic because I hadn't checked if it was specific to Texas hold em or could be applied broadly to all poker games. This is an area I'd definitely like to clean up a bit if I have time in the future. Or feel free to make a PR yourself if you find it interesting enough!

**Comment by Allybag** [comment]
Ah cool, looks legit!

**Comment by winstonrc** [comment]
Great catch on your end! I had a faulty test I wrote on my misunderstanding above that made it look like things were working ok. The test in question:

https://github.com/winstonrc/casino/blob/6496303136201a715dbcf26182d50efac1ea93be/crates/casino_poker/src/hand_rankings.rs#L2386

This test checked that if players had the fifth card in their hand to make a Flush, they both pushed. I now understand that is an impossible situation since both players cannot have identical cards in their hand. Therefore, the player with the higher card in their hand should have the winning Flush.

I'm working on a fix for this now.
